class Model_ObjectDefinitionFields:
    item_id = ""
    Code = ""
    Name = ""
    Database_Field_Name = ""
    Maximum_Length = ""
    Data_Type = ""
    Valid_Values_Source = ""
    Hide_Old_Value = ""
    Decimal_Precision = ""
    Include_Inactive_Users = ""
    UI_Field_Renderer = ""
    Transient = ""
    Help_Text = ""
    Mask_Value_on_UI = ""
    Show_Trailing_Zeros = ""
    Default_Value = ""
    Hide_Seconds = ""
    Required = ""
    Visibility = ""
    Status = ""
    Label = ""
    Cascade = ""
    Inactivated_By = ""
    End_Of_Period = ""


class Processing_ObjectDefinitionFieldsStatus:
    item_id = ""
    Unique_Code = ""
    Processing_Status = ""
